# Generated by Django 3.0.6 on 2020-06-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
