# Generated by Django 3.0.6 on 2020-06-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('mentees', models.ManyToManyField(to='api.User')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Mentor')),
            ],
        ),
    ]
